---
config:
  theme: redux-color
  look: handDrawn
---
sequenceDiagram
    actor Developer
    participant Platform
    participant GameFactory/GameRegistry
    participant Ethereum/Solana

    Developer->>Platform: Register new game
    Platform->>Platform: Generate Solana and Ethereum keypair
    Platform->>GameFactory/GameRegistry: createGame(name, game_pub_key, royalty, uri...)
    GameFactory/GameRegistry->>Ethereum/Solana: createGame()

    Ethereum/Solana-->>Platform: Game data registered on-chain
    Platform-->>Developer: Game registered